config/routes.rb
Rails.application.routes.draw do
  resources :polls, except: %i[show new] do
    resources :options, only: %i[create update destroy]
    resource :respond, only: %i[show create]
    resource :visualization, only: %i[show]
  end

  root "polls#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :poll

  validates :title, presence: true
end

app/models/poll.rb
class Poll < ApplicationRecord
  has_many :options, dependent: :destroy

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_poll
  before_action :set_option, except: :create

  def create
    @option = @poll.options.build(option_params)

    if @option.save
      redirect_to edit_poll_path(@poll), notice: "Option was successfully created."
    else
      redirect_to edit_poll_path(@poll, @option), status: :unprocessable_entity
    end
  end

  def update
    if @option.update(option_params)
      redirect_to edit_poll_path(@poll), notice: "Option was successfully updated."
    else
      redirect_to edit_poll_path(@poll, @option), status: :unprocessable_entity
    end
  end

  def destroy
    @option.destroy

    redirect_to edit_poll_path(@poll), notice: "Option was successfully destroyed."
  end

  private
    def set_option
      @option = Option.find(params[:id])
    end

    def set_poll
      @poll = Poll.find(params[:poll_id])
    end

    def option_params
      params.require(:option).permit(:title, :vote_count)
    end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, except: [ :index, :create ]

  def index
    @polls = Poll.all.order(id: :desc)
  end

  def edit
  end

  def create
    @poll = Poll.new(poll_params)

    if @poll.save
      redirect_to edit_poll_path(@poll), notice: "Poll was successfully created."
    else
      redirect_to polls_path(@poll), status: :unprocessable_entity
    end
  end

  def update
    if @poll.update(poll_params)
      redirect_to edit_poll_path(@poll), notice: "Poll was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @poll.destroy

    redirect_to polls_url, notice: "Poll was successfully destroyed."
  end

  private
    def set_poll
      @poll = Poll.find(params[:id])
    end

    def poll_params
      params.require(:poll).permit(:title)
    end
end

app/controllers/responds_controller.rb
class RespondsController < ApplicationController
  before_action :set_poll

  private
    def set_poll
      @poll = Poll.find(params[:poll_id])
    end
end

app/controllers/visualizations_controller.rb
class VisualizationsController < ApplicationController
  before_action :set_poll

  def show
  end

  private
    def set_poll
      @poll = Poll.find(params[:poll_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/options_helper.rb
module OptionsHelper
  # The poll has two options: "Happy" and "Sad". If "Happy" has received three votes
  # and "Sad" as received one vote, this function will return 75% (3/4) for the "Happy"
  # option and 25% (1/4) for the "Sad" option.
  def percentage_of_total_votes(option, poll)
    total_votes = poll.options.sum(&:vote_count)
    return '0%' if total_votes.zero?

    quotient = option.vote_count.to_f / total_votes

    number_to_percentage(
      quotient * 100,
      precision: 1,
      strip_insignificant_zeros: true
    )
  end

  # The poll has two options: "Happy" and "Sad". If "Happy" has received three votes
  # and "Sad" as received one vote, this function will return 100% (3/3) for the "Happy"
  # option and 33.3333% (1/3) for the "Sad" option.
  def percentage_of_max_votes(option, poll)
    max_votes = poll.options.pluck(:vote_count).max
    return '0%' if max_votes.zero?

    quotient = option.vote_count.to_f / max_votes

    number_to_percentage(quotient * 100)
  end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class='antialiased min-h-full'>
  <head>
    <title>PollAnywhere</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='min-h-full'>
    <div class='flex'>
      <main class='w-full'>
        <div class="w-3/4 place-content-center mx-auto pb-4">
          <h1 class="text-3xl underline hover:no-underline inline">
            <%= link_to "Polls", root_url %>
          </h1>
        </div>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/options/_new.html.erb
<%= form_with model: [poll, Option.new], class: "flex" do |form| %>
  <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none mr-1 w-full" %>
  <%= form.submit "Create option", class: "rounded-lg py-3 px-5 white inline-block font-medium cursor-pointer" %>
<% end %>

app/views/options/_option.html.erb
<div class='flex items-center'>
  <div class='w-full'>
    <div class='text-gray-700 text-3xl'>
      <%= option.title %>
    </div>
  </div>
</div>

app/views/polls/_form.html.erb
<%= form_with(model: poll, class: "contents") do |form| %>
  <% if poll.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
        <% poll.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex mt-3">
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none mr-1 w-full" %>
    <%= form.submit poll.id ? "Update title" : "Create poll", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>
<% if poll.id %>
  <div class="my-5">
    <div class="items-center mb-2">
      <%= render partial: 'polls/options', collection: poll.options, as: :option %>
    </div>
  </div>

  <div class="mb-5">
    <%= render "options/new", poll: poll %>
  </div>
<% end %>

app/views/polls/_options.html.erb
<div class="flex mb-3">
  <%= form_with model: [option.poll, option], class: "flex w-full" do |form| %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none mr-1 w-full" %>
    <%= form.submit "Update", class: "rounded-lg py-3 px-5 white block font-medium cursor-pointer" %>
  <% end %>
  <%= button_to 'Destroy', poll_option_path(option.poll, option), method: :delete, class: "rounded-lg ml-1 py-3 px-5 bg-red-200 font-medium" %>
</div>

app/views/polls/_poll.html.erb
<div id="<%= dom_id poll %>" class='p-10 shadow-lg rounded-md w-full h-full'>
  <h1 class="block text-4xl font-bold text-gray-700">
    <%= poll.title %>
  </h1>
  <div id='poll_<%= poll.id %>_options' class='items-center mt-8 space-y-10'>
    <%= render poll.options %>
  </div>
  <div class='mt-8 space-x-2'>
    <%= link_to "Show this poll", poll_visualization_path(poll), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this poll', edit_poll_path(poll), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/polls/edit.html.erb
<div class="w-3/4 place-content-center mx-auto">
  <h1 class="font-bold text-4xl">Editing poll</h1>
  <%= render "form", poll: @poll %>
  <%= link_to "Show this poll", poll_visualization_path(@poll), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/polls/index.html.erb
<div class="w-3/4 place-content-center mx-auto">
  <%= render "form", poll: Poll.new %>

  <hr class="my-8">
  <div class="min-w-full space-y-8">
    <% @polls.each do |poll| %>
      <%= render poll %>
    <% end %>
  </div>
</div>

app/views/visualizations/show.html.erb
<div class="w-3/4 place-content-center mx-auto">
  <div class='flex space-x-8 h-full'>
    <%= render @poll %>
  </div>
</div>